### ISSUE TITLE
어떤 프로그램인가요?

### ISSUE THREAD

**Issue by devFallingstar** [snaag/issue-and-twitter#2]
단순히 특정 단어에 대해서만 크롤링 하는건가요? 아니면 trending now와 같이 그날 그별 이슈도 트래킹 하나요?

**Comment by snaag** [comment]
음 일단 메인 기능은 특정 지역(이를테면 홍대입구) 을 검색하면, 특정 지역과 관련한 트윗들 (tweet1: 홍대입구에 아이유 왔대!! tweet2: 홍대입구에 아이유뜸... 대박, tweet3: 홍대입구에 아이유있음 역시존예 ..) 들을 크롤링해서 **가장 빈도수가 높은 단어**를 **키워드**로 보여주는 기능을 제공하려고 합니다.

**Comment by devFallingstar** [comment]
오 그렇군요!
라이브러리화 해주신다면 더 큰 도움이 될 것 같습니다!

답변 고맙습니다~
